### ISSUE TITLE
keyerror:'hadm_id'

### ISSUE THREAD

**Issue by JianhaoLuo** [onlyzdd/clinical-fusion#3]
Hi, I'm trying to run your code, and when I run 01_get_signals.py, I got an error keyerror:'hadm_id' in line 12.

**Comment by onlyzdd** [comment]
Hi @JianhaoLuo! The _pivoted_vital_ view should merge with the _icustays_ table. I've updated the _pivoted_vital.sql_ file and it should generate with the _hadm_id_ column now.
